{ user:
  { id: 8,
  username: 'joe_3',
  avatar_template: '/letter_avatar_proxy/v2/letter/j/ba9def/{size}.png',
  name: 'Joe+3',
  last_posted_at: null,
  last_seen_at: '2016-12-31T00:20:22.032Z',
  created_at: '2016-12-30T23:08:49.503Z',
  website_name: null,
  can_edit: true,
  can_edit_username: true,
  can_edit_email: true,
  can_edit_name: true,
  stats: [ [Object] ],
  can_send_private_messages: true,
  can_send_private_message_to_user: true,
  trust_level: 1,
  moderator: false,
  admin: true,
  title: 'Hey I\'m Joe',
  uploaded_avatar_id: null,
  badge_count: 1,
  has_title_badges: false,
  custom_fields: {},
  pending_count: 0,
  profile_view_count: 2,
  primary_group_name: 'Haberdashers',
  primary_group_flair_url: null,
  primary_group_flair_bg_color: null,
  primary_group_flair_color: null,
  post_count: 0,
  can_be_deleted: false,
  can_delete_all_posts: false,
  locale: 'en',
  muted_category_ids: [],
  watched_tags: [],
  watching_first_post_tags: [],
  tracked_tags: [],
  muted_tags: [],
  tracked_category_ids: [],
  watched_category_ids: [],
  watched_first_post_category_ids: [],
  private_messages_stats: { all: 1, mine: 0, unread: 1 },
  system_avatar_upload_id: null,
  system_avatar_template: '/letter_avatar_proxy/v2/letter/j/ba9def/{size}.png',
  gravatar_avatar_upload_id: null,
  gravatar_avatar_template: null,
  custom_avatar_upload_id: null,
  custom_avatar_template: null,
  muted_usernames: [],
  mailing_list_posts_per_day: 0,
  can_change_bio: true,
  user_api_keys: null,
  invited_by: null,
  groups: [ [Object], [Object], [Object], [Object], [Object] ],
  group_users: [ [Object], [Object], [Object], [Object], [Object] ],
  featured_user_badge_ids: [ 9 ],
  card_badge: null,
  user_option:
  { user_id: 8,
    email_always: false,
    mailing_list_mode: false,
    mailing_list_mode_frequency: 0,
    email_digests: true,
    email_private_messages: true,
    email_direct: true,
    external_links_in_new_tab: false,
    dynamic_favicon: false,
    enable_quoting: true,
    disable_jump_reply: false,
    digest_after_minutes: 1440,
    automatically_unpin_topics: true,
    auto_track_topics_after_msecs: 240000,
    notification_level_when_replying: 2,
    new_topic_duration_minutes: 2880,
    email_previous_replies: 2,
    email_in_reply_to: true,
    like_notification_frequency: 1,
    include_tl0_in_digests: false } } }
