{ host: 'circle-discourse.herokuapp.com',
  connection: 'close',
  'user-agent': 'Discourse/1.7.0.beta11',
  accept: '*/*',
  'content-type': 'application/json',
  'x-discourse-instance': 'http://forum.practitionerscircle.org',
  'x-discourse-event-id': '10',
  'x-discourse-event-type': 'post',
  'x-discourse-event': 'post_created',
  'x-request-id': '8e759b0c-4bd8-4e22-965b-eb892712fe39',
  'x-forwarded-for': '159.203.98.98',
  'x-forwarded-proto': 'https',
  'x-forwarded-port': '443',
  via: '1.1 vegur',
  'connect-time': '0',
  'x-request-start': '1492953983689',
  'total-route-time': '0',
  'content-length': '10317' }
